sudo: required
services:
- docker
language: bash
script:
# enable qemu
-  docker run --rm --privileged multiarch/qemu-user-static:register
# build images
- docker build -f Dockerfile.arm -t kurai/jankenpon-game-instance-arm .
#- docker build -f Dockerfile.amd64 -t kurai/jankenpon-game-instance-amd64 .

# push images
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker push kurai/jankenpon-game-instance-arm
    #docker push kurai/jankenpon-game-instance-amd64
  fi
